---
    - name: Setup Blog
      hosts: all
      vars:
        # TODO: Add check later, if current_branch is an empty string then default to master repo
        current_branch: "{{ lookup('env', 'CURRENT_BRANCH') }}"
      tasks:
          - name: Add Docker GPG apt Key
            become: true
            apt_key:
              url: https://download.docker.com/linux/ubuntu/gpg

          - name: Add Docker Repository
            become: true
            apt_repository:
              repo: deb https://download.docker.com/linux/ubuntu focal stable

          - name: Install dependencies
            become: true
            apt:
              package:
                - apt-transport-https
                - ca-certificates
                - curl
                - software-properties-common
                - python3-pip
                - virtualenv
                - python3-setuptools
                - git
                - docker-ce
                - python3-docker
              state: latest
              update_cache: true    

          - name: Login to Github Container Registry
            become: true
            community.docker.docker_login:
              username: "{{ GHCR_USERNAME }}"
              password: "{{ GHCR_TOKEN }}"
              registry_url: https://ghcr.io/shorttoground/shorttoground-blog

          - name: checkout repo
            git:
              repo: 'https://github.com/ShortToGround/shorttoground-blog.git'
              dest: /tmp/shorttoground-blog
              version: "{{ current_branch }}"
              force: true
              
          - name: Remove older version of blog container
            become: true
            docker_container:
              name: shorttoground-blog-container
              state: absent

          - name: Pull and start blog container
            become: true
            docker_container:
              name: shorttoground-blog-container
              image: ghcr.io/shorttoground/shorttoground-blog-container:latest
              pull: true
              expose:
                - 8080
              ports: 
                - '0.0.0.0:80:8080'

          # Logs out of GHCR, which should delete the plain text ghcr token stored on the host
          - name: Logout of Github Container Registry
            become: true
            community.docker.docker_login:
              registry_url: https://ghcr.io/shorttoground/shorttoground-blog
              state: absent