---
    - name: Setup Blog
      hosts: all
      tasks:

          - name: Install dependencies
            become: true
            apt:
              package:
                - apt-transport-https
                - ca-certificates
                - curl
                - software-properties-common
                - python3-pip
                - virtualenv
                - python3-setuptools
                - git
              state: latest
              update_cache: true    
            
            
          - name: Add Docker GPG apt Key
            become: true
            apt_key:
              url: https://download.docker.com/linux/ubuntu/gpg
              state: present

          - name: Add Docker Repository
            become: true
            apt_repository:
              repo: deb https://download.docker.com/linux/ubuntu focal stable
              state: present

          - name: Update/upgrade apt packages
            become: true
            apt:
              update_cache: yes
              upgrade: yes
              
          - name: Install docker package
            become: true
            apt:
              package:
                - docker-ce
              state: latest

          - name: Install Python Docker Module
            become: true
            apt:
              package:
                  - python3-docker
              state: latest

          - name: Login to Github Container Registry
            become: true
            community.docker.docker_login:
              username: "{{ GHCR_USERNAME }}"
              password: "{{ GHCR_TOKEN }}"
              registry_url: https://ghcr.io/shorttoground/shorttoground-blog

          - name: checkout repo
            git:
              repo: 'https://github.com/ShortToGround/shorttoground-blog.git'
              dest: /tmp/shorttoground-blog
            
          - name: Remove older version of blog container
            become: true
            docker_container:
              name: shorttoground-blog-container
              state: absent

          - name: Pull and start blog container
            become: true
            docker_container:
              name: shorttoground-blog-container
              image: ghcr.io/shorttoground/shorttoground-blog-container:latest
              state: started
              expose:
                - 8080
              ports: 
                - '0.0.0.0:80:8080'

          # Logs out of GHCR, which should delete the plain text ghcr token stored on the host
          - name: Logout of Github Container Registry
            become: true
            community.docker.docker_login:
              registry_url: https://ghcr.io/shorttoground/shorttoground-blog
              state: absent